export default {

	LOGIN_USER: 'LOGIN_USER',
	LOGOUT_USER: 'LOGOUT_USER',

	SIGNUP_USER: 'SIGNUP_USER',

	AUTH_SIGNIN: 'AUTH_SIGNIN',
   AUTH_SIGNIN_SUCCESS: 'AUTH_SIGNIN_SUCCESS',
   AUTH_SIGNIN_FAIL: 'AUTH_SIGNIN_FAIL',

   AUTH_SIGNOUT: 'AUTH_SIGNOUT',
   AUTH_SIGNOUT_SUCCESS: 'AUTH_SIGNOUT_SUCCESS',
   AUTH_SIGNOUT_FAIL: 'AUTH_SIGNOUT_FAIL',

   AUTH_SIGNUP_SUCCESS: 'AUTH_SIGNUP_SUCCESS',
   AUTH_SIGNUP: 'AUTH_SIGNUP',
   AUTH_SIGNUP_FAIL: 'AUTH_SIGNUP_FAIL',

   RECEIVE_TEAMS: 'RECEIVE_TEAMS',

   RECEIVE_USER: 'RECEIVE_USER'

}